# USING NODEJS AS WEB SERVER
FROM node:16.18.0-alpine

# CREATE A WORKING DIRECTORY
WORKDIR /app

# COPY ALL CONTENT TO THE DIRECTORY ABOVE
COPY . .

# INSTALL THE PACKAGES
RUN npm install

# BUILD THE APP
RUN npm run build

# RUN THE BUILD FILES
ENTRYPOINT ["npm", "run", "start"]